### ISSUE TITLE
SCK 2.1 DIY Clips | New battery case

### ISSUE THREAD

**Issue by bitvijays** [fablabbcn/smartcitizen-enclosures#6]
Dear Smart Citizen Kit Team,

Hope you are doing well and thank you for creating a amazing SCK kit. 

Currently, we have SCK Kit 2.1 which comes with a different battery than the SCK 2.0.  Battery of 2.0 is slimmer and bigger than battery of 2.1.

The [clips of SCK2.1](https://github.com/fablabbcn/smartcitizen-enclosures/blob/master/SmartCitizen%20DIY%20Clips%20V2.0-2.1/3D%20Print%20Clips.stl) enclosures are probably created for 2.0 and not 2.1 battery?

Would it be possible to provide Clips 2.1 with battery which is smaller and thicker?

Yours Sincerely,
Vijay

**Comment by oscgonfer** [comment]
Hi!

The clips in the SCK2.1 are meant for a small 2000mAh battery. This image shows clearly how they are put together:
https://www.flickr.com/photos/smartcitizen/51139782953/

In the case of SCK2.0, the battery then was larger in footprint but thinner. The clips (which I wouldn't recommend using) held the battery like so:
https://www.flickr.com/photos/smartcitizen/45269792052/

The battery in this latter case is held and potentially pressed by the clips, not leaving room for dilatation. Let us know if, with these comments, the SCK2.1 clips work now (we moved them here):  https://github.com/fablabbcn/smartcitizen-enclosures/blob/master/SmartCitizen%20Outdoor%20Cases%20V2.*/SCK2.1_PMS5003/HDPE%20circle/components/CLIP_NO_ORING.stl

**Comment by bitvijays** [comment]
Thank you @oscgonfer 👍 That's really helpful.
